#!/usr/bin/env python3
"""
Morning Briefing System for Larry
Generates daily summaries with overnight progress, jobs, calendar, weather
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path

# Paths
DASHBOARD_DIR = Path("/Users/tommylu/clawd/dashboard")
STATUS_FILE = DASHBOARD_DIR / "larry-status.json"
JOB_TRACKER = Path("/Users/tommylu/clawd/job-search/tracker.json")
MEMORY_DIR = Path("/Users/tommylu/clawd/memory")
OUTPUT_DIR = DASHBOARD_DIR / "briefing"

def load_json(path):
    """Load JSON file safely"""
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return {}

def get_today_memory():
    """Get today's memory file"""
    today = datetime.now().strftime("%Y-%m-%d")
    memory_file = MEMORY_DIR / f"{today}.md"
    if memory_file.exists():
        with open(memory_file, 'r') as f:
            return f.read()
    return None

def format_briefing():
    """Generate morning briefing"""
    now = datetime.now()
    today_str = now.strftime("%Y-%m-%d")
    weekday = now.strftime("%A")
    date_display = now.strftime("%B %d, %Y")

    # Load data sources
    status = load_json(STATUS_FILE)
    job_tracker = load_json(JOB_TRACKER)
    memory_content = get_today_memory()

    # Extract key info
    streak = status.get("stats", {}).get("streak", 0)
    today_completed = len([t for t in status.get("tasks", {}).get("done", []) if "2026-02-01" in t.get("completed", "")])

    # Recent activity
    recent_activity = status.get("activity", [])[:8]  # Last 8 items

    # Job search stats
    job_apps = job_tracker.get("applications", [])
    total_jobs = len(job_apps)
    applied_jobs = [j for j in job_apps if j.get("status") == "applied"]
    discovered_jobs = [j for j in job_apps if j.get("status") == "discovered"]

    # Build briefing
    briefing = f"""# 🌅 Morning Briefing
**{weekday}, {date_display}** | Est. Time: {now.strftime("%-I:%M %p")} | Streak: 🔥 {streak} days

---

## 🎯 Overnight Progress ({today_completed} tasks done)

"""

    # Add completed tasks from today
    today_done = [t for t in status.get("tasks", {}).get("done", []) if t.get("completed", "").startswith("2026-02-01")]
    if today_done:
        for task in today_done:
            time = task.get("completed", "")[11:16]
            briefing += f"- ✅ [{time}] {task.get('title', 'Unknown')} ({task.get('category', 'system')})\n"
    else:
        briefing += "No tasks completed overnight.\n"

    briefing += f"""
---

## 💼 Job Search Update
**Total tracked:** {total_jobs} | **Applied:** {len(applied_jobs)} | **Discovered:** {len(discovered_jobs)}

"""

    # Recent job discoveries
    if discovered_jobs:
        briefing += "**New Opportunities:**\n"
        for job in discovered_jobs[-3:]:  # Last 3 discovered
            briefing += f"- 📌 {job.get('company')} - {job.get('role')}\n"

    # Recent applications
    if applied_jobs:
        briefing += "\n**Recently Applied:**\n"
        for job in applied_jobs[-3:]:  # Last 3 applied
            briefing += f"- ✅ {job.get('company')} - {job.get('role')}\n"

    briefing += f"""
---

## 📋 Dashboard Backlog ({len(status.get('tasks', {}).get('backlog', []))} items)

High priority due today:
"""

    # High priority tasks due today
    backlog = status.get("tasks", {}).get("backlog", [])
    high_priority = [t for t in backlog if t.get("priority") == "high" and t.get("dueDate", "").startswith("2026-02-01")]

    if high_priority:
        for task in high_priority:
            briefing += f"- ⚡ {task.get('title')} ({task.get('estimatedMinutes', '?')} min)\n"
    else:
        briefing += "No high-priority tasks due today.\n"

    briefing += """
---

## 💻 System Status

| System | Status |
|--------|--------|
| Larry Dashboard | 🟢 Running |
| MAG7 Trading Bot | 🟢 Healthy |
| Forex Trading Bot | 🟢 Healthy |
| Voice Chat | 🟢 Ready (localhost:8888/voice-chat/) |

---

## 📝 Today's Notes

"""

    # Add memory content if available
    if memory_content:
        # Extract key events from memory
        lines = memory_content.split('\n')
        in_key_events = False
        for line in lines:
            if "## Key Events" in line:
                in_key_events = True
                continue
            if in_key_events and line.strip():
                if line.startswith("## "):
                    break
                briefing += line + "\n"
    else:
        briefing += "No new notes from overnight.\n"

    briefing += f"""
---

*Generated by Larry at {now.strftime("%-I:%M %p")} EST*
"""

    return briefing

def save_briefing(briefing):
    """Save briefing to file"""
    OUTPUT_DIR.mkdir(exist_ok=True)
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%H%M")

    # Save both dated and latest versions
    dated_file = OUTPUT_DIR / f"briefing-{date_str}.md"
    latest_file = OUTPUT_DIR / "briefing-latest.md"

    with open(dated_file, 'w') as f:
        f.write(briefing)

    with open(latest_file, 'w') as f:
        f.write(briefing)

    print(f"✅ Briefing saved to {dated_file}")
    print(f"✅ Latest briefing at {latest_file}")

    return latest_file

if __name__ == "__main__":
    print("🌅 Generating morning briefing...")
    briefing = format_briefing()
    save_briefing(briefing)
    print("\n" + "="*50)
    print(briefing)
